### ISSUE TITLE
serverinfo command could someone help me

### ISSUE THREAD

**Issue by ShockAnWave** [sandarutharuneth/ivongiveaways#24]
```
C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:157
    if (!this.deferred && !this.replied) throw new DiscordjsError(ErrorCodes.InteractionNotReplied);
                                               ^

Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.editReply (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:157:48)
    at Object.run (C:\Users\Administrator\Desktop\ivongiveaways-main\slash\serverinfo.js:46:19)
    at module.exports (C:\Users\Administrator\Desktop\ivongiveaways-main\events\discord\interactionCreate.js:14:13)
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:494:22)
    at WebSocketShard.onMessage (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\Administrator\Desktop\ivongiveaways-main\node_modules\ws\lib\event-target.js:290:14) {
  code: 'InteractionNotReplied'
}
```

**Comment by sandarutharuneth** [comment]
The error cause due to the lack of permissions on the bot or the command used channel. Please check if you given the right permissions to the test bot or if you given the normal permissions to your test channel. I have suppress the error yesterday. If you have old code from my git, please re download and run.

**Comment by sandarutharuneth** [comment]
> i have already re downloaded grant the bot admin perms and set channel perms too and still the same issue

Please double check. I've pushed error suppression to serverinfo.
