### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ShockAnWave** [sandarutharuneth/ivongiveaways#27]
```
giveaway\node_modules\discord-giveaways\src\Manager.js:76
            .setTitle(typeof giveaway.messages.title === 'string' ? giveaway.messages.title : giveaway.prize)
                                               ^

TypeError: Cannot read properties of undefined (reading 'title')
    at GiveawayManagerCustom.generateMainEmbed (C:\Users\sixpa\OneDrive\Desktop\giveaway\node_modules\discord-giveaways\src\Manager.js:76:48)
    at C:\Users\sixpa\OneDrive\Desktop\giveaway\node_modules\discord-giveaways\src\Manager.js:596:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by sandarutharuneth** [comment]
This is not an error from the code. It's a issue on the giveaways npm package. Either you tried to customize it and broke it or genuine issue on the giveaway package. Try reinstalling the package or check the discord-giveaways package code for any known issue.
