### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by sidboy55555** [sandarutharuneth/ivongiveaways#32]
Hi,

When I try to start this bot I get a few errors and a invalid token error, while the token in the .env is valid.

Not sure what's going on here..
`root@pterodata:/srv/bots/giveaway# node index.js
{MongoDB Event Handler} - "connected" event registered.
{MongoDB Event Handler} - "connecting" event registered.
{MongoDB Event Handler} - "disconnedted" event registered.
{MongoDB Event Handler} - "err" event registered.
(node:25464) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
[MONGO DB]: Error: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
/srv/bots/giveaway/node_modules/discord.js/src/client/Client.js:216
    if (!token || typeof token !== 'string') throw new DiscordjsError(ErrorCodes.TokenInvalid);
                                                   ^

Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/srv/bots/giveaway/node_modules/discord.js/src/client/Client.js:216:52)
    at Object.<anonymous> (/srv/bots/giveaway/index.js:112:8)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'TokenInvalid'
}

Node.js v20.5.1`

**Comment by sandarutharuneth** [comment]
Please check that all your bot intents are turn on, check your db allows connection from everywhere and check the index.js file if your token get called from the .env file instead of the config file.

**Comment by sidboy55555** [comment]
Hi,

All intents are on. And is mongodb required? Since I only use mysql/mariadb.

And after pasting the token also in the config.json the bot gives an api error now instead.
`
root@pterodata:/srv/bots/giveaway# node index.js

{MongoDB Event Handler} - "connected" event registered.
{MongoDB Event Handler} - "connecting" event registered.
{MongoDB Event Handler} - "disconnedted" event registered.
{MongoDB Event Handler} - "err" event registered.
(node:25574) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
[MONGO DB]: Error: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[Event]   🎉 Loaded: endedGiveawayReactionAdded
[Event]   🎉 Loaded: giveawayEnded
[Event]   🎉 Loaded: giveawayReactionAdded
[Event]   🎉 Loaded: giveawayReactionRemoved
[Event]   🎉 Loaded: giveawayRerolled
[Event]   ✅  Loaded: interactionCreate
[Event]   ✅  Loaded: messageCreate
[Event]   ✅  Loaded: ready
/srv/bots/giveaway/node_modules/japi.rest/src/index.js:27
    if (typeof this.key !== 'string' || !/^JAPI\..{50,54}$/.test(this.key)) throw new Error('Invalid API Key');
                                                                            ^

Error: Invalid API Key
    at JAPIRest.checkKey (/srv/bots/giveaway/node_modules/japi.rest/src/index.js:27:83)
    at new JAPIRest (/srv/bots/giveaway/node_modules/japi.rest/src/index.js:7:10)
    at Object.<anonymous> (/srv/bots/giveaway/slash/userinfo.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /srv/bots/giveaway/index.js:101:17

Node.js v20.5.1
`

**Comment by sandarutharuneth** [comment]
You have been using the old code on my repo. remove the `userinfo.js` file to get rid of the API issue. For my code infrastructure it's a MUST for the MongoDB to function the bot since it handle and store all the giveaway data. If you want to use a separate DB you'll have to recode the bot from ground up.
